[package]
name = "cj_ascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cj_ascii"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["serde"]
serialize = ["serde"]

[dev-dependencies]
serde_json = "1.0"

